# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt


    providers:
        db_provider:
            entity:
                class: AppBundle:Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                csrf_provider: security.csrf.token_manager

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
